mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path('', views.home, name='home'),
    path('skill/', views.skill, name='skill'),
    path('workplay/', views.workplay, name='workplay'),
    path('message/', views.message, name='message'),
    path('thankyou/', views.ty, name='ty'),

    path('form/', views.form, name='form'),
    path('show/', views.show, name='show'),
    path('delete-activity/<int:pk>/', views.delete_activity, name='delete_activity'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mypage.urls')),

]

mypage/models.py
from django.db import models


class ScheduleModel(models.Model):
    date = models.DateField()
    time = models.TimeField(auto_now_add=False)
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=50)

    def __str__(self):
        return "{}.{}".format(self.id, self.name)

mypage/forms.py
from django import forms
from .models import ScheduleModel
import datetime


class ScheduleForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={
            "placeholder": "Project's Title",
        }
    ))
    category = forms.CharField(widget=forms.TextInput(
        attrs={
            "placeholder": "Project's Category",
        }
    ))
    date = forms.DateField(input_formats=['%Y-%m-%d'], initial=datetime.date.today(), widget=forms.TextInput(attrs=
    {
        'class': 'form-control'
    }))

    time = forms.TimeField(input_formats=['%H:%M:%S'], initial=datetime.time, widget=forms.TextInput(attrs=
    {
        'class': 'form-control'
    }))

    class Meta:
        model = ScheduleModel
        fields = [
            'date',
            'time',
            'name',
            'category',
        ]

mypage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ScheduleForm
from .models import ScheduleModel
from django.contrib import messages


def home(request):
    return render(request, 'home.html')


def skill(request):
    return render(request, 'skill.html')


def workplay(request):
    return render(request, 'workplay.html')


def message(request):
    return render(request, 'message.html')


def ty(request):
    return render(request, 'ty.html')


def show(request):
    data = ScheduleModel.objects.all()
    return render(request, 'result.html', {'data': data})


def form(request):
    if request.method == "POST":
        data = ScheduleForm(request.POST)
        if data.is_valid():
            data.save()
            return redirect('mypage:show')
        else:
            messages.warning(request, 'Data input is not valid, Please try again!')

    else:
        data = ScheduleForm()


    return render(request, 'form.html', {'form': data})


def delete_activity(request, pk):
    activity = get_object_or_404(ScheduleModel, pk=pk)
    activity.delete()


    return redirect('mypage:show')

mypage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

	    <title>Fathinah Asma</title>

		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

	</head>
	<body>

		<nav class="navbar navbar-expand-lg navbar-light nav-color navbar-right">
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse right" id="navbarNav">
		    <ul class="navbar-nav ">
		      <li class="nav-item active">
		        <a class="nav-link" href="{% url 'mypage:home' %}">HOME </a>
		      </li>
		      <!--sr only gue apus diatas-->
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'mypage:skill' %}">SKILLS</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'mypage:workplay' %}">WORK & PLAY</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'mypage:message' %}">CONTACT</a>
		      </li>
                <li class="nav-item">
		        <a class="nav-link" href="{% url 'mypage:form' %}">FORM</a>
		      </li>
                <li class="nav-item">
		        <a class="nav-link" href="{% url 'mypage:show' %}">SHOW FORM</a>
		      </li>

		    </ul>
		  </div>
		</nav>

		{% block content %}
		{% endblock %}
	</body>
</html>

mypage/templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <h3>Add a reminder</h3>

        <form action="/form/" method="POST">
            {% csrf_token %}
            <table>
                <tr>
                    {{ form.as_table }}
                </tr>

            </table>
            {% with url_name=request.resolver_match.url_name %}
                <button class="btn-success" type="submit">Add</button>
                </form>

            {% endwith %}

{% endblock %}

mypage/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<div class = "container">
			<div id="socmed">
				<a href="https://instagram.com/fa.thina/"><img src="{% static 'images/ig.png' %}"></a>
				<a href="https://github.com/cruncheek"><img src="{% static 'images/github.png' %}"></a>
				<a href="https://medium.com/@cruncheek"><img class="gml" src="{% static 'images/gmail.png' %}"></a>
			</div>
			<div id="main">
				 <h1>HI, I’M THINA</h1>
				 <hr>
				 <p>I’m a second year student majoring in Computer Science</p>
			</div>
		</div>
		
			
		
{% endblock %}

mypage/templates/message.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<div class = "container">
			<div id="socmed">
				<a href="https://instagram.com/fa.thina/"><img src="{% static 'images/ig.png' %}"></a>
				<a href="https://github.com/cruncheek"><img src="{% static 'images/github.png' %}"></a>
				<a href="https://medium.com/@cruncheek"><img class="gml" src="{% static 'images/gmail.png' %}"></a>
			</div>
			<div id="main">
				<div class="container-form">
				  <form action="{% url 'mypage:ty' %}">
				    <div class="col-75">
				      <input type="text" id="fname" name="firstname" placeholder="Email Address">
				    </div>
				    <div class="col-75">
				      <input type="text" id="lname" name="lastname" placeholder="Subject">
				    </div>
				    <div class="col-75">
				      <textarea id="subject" name="subject" placeholder="Your Message" style="height:200px"></textarea>
				    </div>
				  <div id="submit-area">
				    <input type="submit" value="Submit">
				  </div>
				  </form>
				</div>

			</div>
		</div>
		
			
{% endblock %}

mypage/templates/result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div style="text-align: center">
        <h3>Fathinah's Schedule</h3>
        <table class="table">
            <thead>
            <tr>
                <th> No </th>
                <th>Activity</th>
                <th>Category</th>
                <!-- <th>Day</th> -->
                <th>Date</th>
                <th>Time</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                {% for i in data %}
                    <tr>
                        <th>{{ forloop.counter}}</th>
                        <td>{{ i.name }}</td>
                        <td>{{ i.category }}</td>
                        <td>{{ i.date }}</td>
                        <td>{{ i.time }}</td>

                        <td><a href="{% url 'mypage:delete_activity' i.pk %}">
                            <button class="btn btn-primary"> Delete</button>
                        </a></td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

mypage/templates/skill.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<div class = "container">
			<div id="socmed">
				<a href="https://instagram.com/fa.thina/"><img src="{% static 'images/ig.png' %}"></a>
				
				<a href="https://github.com/cruncheek"><img src="{% static 'images/github.png' %}"></a>

				<a href="https://medium.com/@cruncheek"><img class="gml" src="{% static 'images/gmail.png' %}"></a>
			</div>
			<div id="main">
				 <img class="circle" src="{% static 'images/pena-bulat.png' %}">
				 <h3 class="desc">WRITING & BLOGGING</h3>
			</div>
		</div>
		
			
		
{% endblock %}

mypage/templates/ty.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<div class = "container">
			<div id="socmed">
				<a href="https://instagram.com/fa.thina/"><img src="{% static 'images/ig.png' %}"></a>
				<a href="https://github.com/cruncheek"><img src="{% static 'images/github.png' %}"></a>
				<a href="https://medium.com/@cruncheek"><img class="gml" src="{% static 'images/gmail.png' %}"></a>
			</div>
			<div id="main">
				<p id="thankyou">Thank you! Your message has been successfully submitted. Gotta get back to you soon! :) <br> Sincerely, <br> Fathinah </p>
			</div>
		</div>
		
			
{% endblock %}

mypage/templates/workplay.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		

		<div class = "container">
			<div id="socmed">
				<a href="https://instagram.com/fa.thina/"><img src="{% static 'images/ig.png' %}"></a>
				<a href="https://github.com/cruncheek"><img src="{% static 'images/github.png' %}"></a>
				<a href="https://medium.com/@cruncheek"><img class="gml" src="{% static 'images/gmail.png' %}"></a>
			</div>
			<div class="block">
				<div id="main-wp">
					 <div class="kotak" id="kotak-ec">
					 	<img src="{% static 'images/ec.JPG' %}">
					 	<h6>A year full of valueable lessons</h6>
					 	<p>Lorem ipsum dolor sit amet, consectetur Duis aute irure  integer tincidunt. Cras dapibus.</p>
					 </div>
					 <div class="kotak">
					 	<img src="{% static 'images/mun.jpg' %}">
					 	<h6>My MUN Journey</h6>
					 	<p>Lorem ipsum dolor sit amet, consectetur Duis aute irur integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.  </p>
					 </div>
					 <div class="kotak">
					 	<img src="{% static 'images/gg.png' %}">
					 	<h6>A day in KL</h6>
					 	<p>Lorem ipsum dolor sit amet, consectetur Duis aute irure integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.</p>
					 </div>
				</div>
				<div id="main-wp">
					 <div class="kotak" id="kotak-ec">
					 	<img src="{% static 'images/ec.JPG' %}">
					 	<h6>A year full of valueable lessons</h6>
					 	<p>Lorem ipsum dolor sit amet, consectetur Duis aute irure  integer tincidunt.</p>
					 </div>
					 <div class="kotak">
					 	<img src="{% static 'images/mun.jpg' %}">
					 	<h6>My MUN Journey</h6>
					 	<p>Lorem ipsum dolor sit amet, consectetur Duis aute irure integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. </p>
					 </div>
					 <div class="kotak">
					 	<img src="{% static 'images/gg.png' %}">
					 	<h6>A day in KL</h6>
					 	<p>Lorem ipsum dolor sit amet, consectetur Duis aute irure integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. </p>
					 </div>
				</div>
			</div>
		</div>
		
			
		
		

		
{% endblock %}